require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'

Style/Documentation:
  Enabled: false
