require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false
